=== TranDoanTriet/test-repo/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="studentID" type="xs:int"/>
        <xs:element name="identityCard" type="xs:int"/>
        <xs:element name="fullName" type="xs:string"/>
        <xs:element name="birthDate" type="xs:date"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="age">
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="18"/>
              <xs:maxInclusive value="100"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="gender">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="male"/>
              <xs:enumeration value="female"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== TranDoanTriet/test-repo/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
  <studentID>12345</studentID>
  <identityCard>987654321</identityCard>
  <fullName>Nguyen Van A</fullName>
  <birthDate>2000-01-01</birthDate>
  <email>nguyenvana@example.com</email>
  <age>22</age>
  <gender>abc</gender>
</student>
